#!/bin/bash
set -eu && [ ${SET_X:-false} = "true" ] && set -x
update() {
    npm run update
    BUILD_VERSION=${CICOMMIT_DEST_REF} npm run build

    git add -u src/ public/
}
export -f update

deploy() {
    npm run deploy
    ## git add は不要
}
export -f deploy

bbcompass_cicommit() {
    local git_cicommit=$(which git-cicommit 2>/dev/null) &&:
    if [ $? -ne 0 ]; then
        git_cicommit=".git-cicommit"
        if [ ! -f ${git_cicommit} ]; then
            wget https://raw.githubusercontent.com/hell0again/git-cicommit/master/git-cicommit -O ${git_cicommit}
        fi
    fi
    source ${git_cicommit}
    cicommit $@
}
[ $(basename -- $0) != "cicommit" ] || bbcompass_cicommit $@

